import React from "react";

export const styles: { [key: string]: React.CSSProperties } = {
appContainer: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#020617",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
  },
  sidebar: {
    width: "320px",
    height: "100%",
    backgroundColor: "#0b1120",
    borderRight: "1px solid #1e293b",
    zIndex: 2000,
    transition: "0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    display: "flex",
    flexDirection: "column",
  },
  sidebarHeader: {
    padding: "24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #1e293b",
  },
  logo: {
    fontSize: "1.2rem",
    fontWeight: 800,
    color: "#6366f1",
    margin: 0,
    cursor: "pointer",
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "white",
    fontSize: 24,
  },
  sessionList: { flex: 1, overflowY: "auto", padding: "16px" },
  sectionLabel: {
    fontSize: "0.7rem",
    fontWeight: 700,
    color: "#475569",
    letterSpacing: "1px",
    marginBottom: "12px",
    paddingLeft: "8px",
  },
  sessionItem: {
    display: "flex",
    alignItems: "center",
    padding: "12px",
    borderRadius: "12px",
    cursor: "pointer",
    marginBottom: "4px",
    transition: "0.2s",
  },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    marginRight: "12px",
    color: "#818cf8",
  },
  sessionInfo: { flex: 1 },
  sessionName: { fontSize: "0.9rem", fontWeight: 600 },
  sidebarFooter: { padding: "16px", borderTop: "1px solid #1e293b" },
  addBtn: {
    width: "100%",
    padding: "14px",
    borderRadius: "10px",
    backgroundColor: "#6366f1",
    border: "none",
    color: "white",
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
  },

  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    position: "relative",
  },
  mainHeader: {
    position: "sticky",
    top: 0,
    zIndex: 100,
    paddingTop: "env(safe-area-inset-top, 16px)",
    paddingLeft: 24,
    paddingRight: 24,
    minHeight: 64,
    display: "flex",
    alignItems: "center",
    borderBottom: "1px solid #1e293b",
    backgroundColor: "rgba(11, 17, 32, 0.8)",
    backdropFilter: "blur(12px)",
  },
  headerTitle: {
    fontSize: "1rem",
    fontWeight: 700,
    margin: 0,
    cursor: "pointer",
  },
  callButtonsContainer: {
    display: "flex",
    gap: "12px",
    marginLeft: "auto",
  },

  iconBtn: {
    background: "none",
    border: "none",
    color: "#94a3b8",
    fontSize: "22px",
    cursor: "pointer",
    padding: "8px",
    borderRadius: "12px",
    transition: "0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  menuBtn: {
    background: "none",
    border: "none",
    color: "white",
    fontSize: 24,
    marginRight: "16px",
    padding: "8px",
    touchAction: "manipulation",
  },
  contentBody: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    overflow: "hidden",
  },
  chatContainer: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  messageArea: {
    flex: 1,
    overflowY: "auto",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  messageRow: { display: "flex", marginBottom: "12px" },
  bubble: {
    padding: "10px 14px",
    borderRadius: "18px",
    maxWidth: "75%",
    fontSize: "0.95rem",
    lineHeight: "1.4",
    boxShadow: "0 2px 5px rgba(0,0,0,0.1)",
    position: "relative",
  },
  inputField: {
    flex: 1,
    background: "none",
    border: "none",
    padding: "12px 16px",
    color: "white",
    outline: "none",
    resize: "none" as "none",
    maxHeight: "150px",
    fontFamily: "inherit",
    fontSize: "0.95rem",
  },
  setupCard: {
    maxWidth: "420px",
    width: "92%",
    alignSelf: "center",
    padding: "32px",
    borderRadius: "24px",
    backgroundColor: "#0b1120",
    border: "1px solid #1e293b",
    textAlign: "center" as "center",
  },
  setupSub: { color: "#94a3b8", fontSize: "0.85rem", marginBottom: "24px" },
  primaryBtn: {
    width: "100%",
    padding: "14px",
    borderRadius: "10px",
    backgroundColor: "#6366f1",
    border: "none",
    color: "white",
    fontWeight: 700,
    cursor: "pointer",
  },
  inviteCodeContainer: {
    marginTop: "20px",
    padding: "20px",
    borderRadius: "12px",
    backgroundColor: "rgba(99, 102, 241, 0.1)",
    border: "1px dashed #6366f1",
    cursor: "pointer",
  },
  codeLabel: {
    fontSize: "0.6rem",
    fontWeight: 800,
    color: "#818cf8",
    marginBottom: "4px",
  },
  codeText: {
    fontSize: "2.2rem",
    letterSpacing: "6px",
    margin: 0,
    color: "white",
  },
  divider: {
    margin: "32px 0",
    textAlign: "center",
    borderBottom: "1px solid #1e293b",
    lineHeight: "0.1em",
  },
  joinRow: { display: "flex", gap: "10px" },
  joinInput: {
    flex: 1,
    backgroundColor: "#020617",
    border: "1px solid #1e293b",
    borderRadius: "10px",
    padding: "12px",
    color: "white",
    textAlign: "center",
    fontSize: "1.1rem",
  },
  connectBtn: {
    padding: "0 20px",
    borderRadius: "10px",
    backgroundColor: "#6366f1",
    border: "none",
    color: "white",
    cursor: "pointer",
    fontWeight: 600,
  },

  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.3,
    textAlign: "center",
  },
  heroIcon: { fontSize: "64px", marginBottom: "16px" },
  mobileOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    zIndex: 1500,
    backdropFilter: "blur(4px)",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 4000,
    backdropFilter: "blur(12px)",
  },
  glassModal: {
    background: "#0b1120",
    border: "1px solid #1e293b",
    padding: "32px",
    borderRadius: "24px",
    width: "90%",
    maxWidth: "340px",
    textAlign: "center",
  },

  iconBtnLarge: {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    border: "none",
    color: "white",
    fontSize: "24px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 12px rgba(0,0,0,0.3)"
  },
  modalButtons: { display: "flex", gap: "12px", marginTop: "24px" },
  cancelBtn: {
    flex: 1,
    padding: "12px",
    background: "transparent",
    border: "1px solid #334155",
    color: "white",
    borderRadius: "10px",
    cursor: "pointer",
  },
  errorToast: {
    position: "fixed",
    top: 20,
    right: 20,
    backgroundColor: "#ef4444",
    padding: "12px 24px",
    borderRadius: "12px",
    zIndex: 5000,
    fontWeight: 700,
  },
  spinner: {
    width: "30px",
    height: "30px",
    border: "3px solid rgba(255,255,255,0.1)",
    borderTopColor: "#6366f1",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    margin: "0 auto 15px",
  },
  callCard: {
    background: "#0b1120",
    border: "1px solid #1e293b",
    padding: "48px 32px",
    borderRadius: "32px",
    width: "90%",
    maxWidth: "360px",
    textAlign: "center",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.5)",
  },
  avatarLarge: {
    width: "100px",
    height: "100px",
    borderRadius: "50%",
    backgroundColor: "#1e293b",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "40px",
    margin: "0 auto",
    border: "4px solid #6366f1"
  },
  callStatus: {
    color: "#94a3b8",
    fontSize: "0.9rem",
    marginBottom: "40px",
    letterSpacing: "0.5px",
  },
  actionCircle: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "24px",
    cursor: "pointer",
    transition: "transform 0.2s",
  },
  // ... existing styles ...,
  // Ensure inputWrapper is relative so the menu positions correctly
  inputWrapper: {
    padding: "12px 16px",
    backgroundColor: "#0b1120",
    borderTop: "1px solid #1e293b",
    position: "relative" as "relative",
  },
  // ... existing styles ...
  plusBtn: {
    background: "none",
    border: "none",
    color: "#94a3b8",
    fontSize: "28px",
    cursor: "pointer",
    padding: "0 12px",
    display: "flex",
    alignItems: "center",
    transition: "0.3s ease",
  },
  attachmentItem: {
    display: "flex",
    flexDirection: "column" as "column",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
  },
  attachmentCircle: {
    width: "56px",
    height: "56px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "22px",
  },
  attachmentLabel: {
    fontSize: "0.75rem",
    color: "#cbd5e1",
    fontWeight: 500,
  },
  // PORT MODAL STYLES
  portModal: {
    position: "absolute",
    bottom: "90px",
    left: "50%",
    transform: "translateX(-50%)",
    width: "280px",
    zIndex: 1100,
  },
  portModalContent: {
    backgroundColor: "#1e293b",
    padding: "20px",
    borderRadius: "18px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.5)",
    border: "1px solid #334155",
  },
  portSendBtn: {
    flex: 1,
    padding: "10px",
    backgroundColor: "#6366f1",
    border: "none",
    color: "white",
    borderRadius: "8px",
    fontWeight: 600,
    cursor: "pointer",
  },
  portCancelBtn: {
    padding: "10px",
    background: "transparent",
    border: "1px solid #334155",
    color: "#94a3b8",
    borderRadius: "8px",
    cursor: "pointer",
  },
  attachmentGrid: {
    position: "absolute",
    bottom: "85px",
    left: "10px",
    right: "10px",
    backgroundColor: "#1e293b",
    borderRadius: "24px",
    padding: "24px",
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    boxShadow: "0 -15px 40px rgba(0,0,0,0.5)",
    zIndex: 1000,
  },
  // Add/Update these in your Home.styles.ts
  plusBtnContainer: {
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#94a3b8",
    fontSize: "26px",
    cursor: "pointer",
    transition: "0.2s ease",
    userSelect: "none",
    flexShrink: 0, // Prevents the icon from squishing
  },
  inputContainer: {
    display: "flex",
    alignItems: "center", // Centered alignment for icons and text
    backgroundColor: "#0f172a",
    borderRadius: "28px",
    border: "1px solid #1e293b",
    padding: "4px 8px",
    position: "relative",
    gap: "4px",
  },
  sendBtn: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#6366f1",
    border: "none",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "18px",
    flexShrink: 0,
    transition: "all 0.2s ease",
  },
  portInput: {
    width: "100%",
    padding: "12px",
    backgroundColor: "#020617",
    border: "1px solid #334155",
    borderRadius: "10px",
    color: "white",
    fontSize: "1rem",
    outline: "none",
    appearance: "none", // Removes arrows in some browsers
  },
};